require('strict').on()

local CONSTANT = {}

CONSTANT.STATUS_INVALID_PARAM   = 'INVALID PARAM'
CONSTANT.STATUS_UNDEFINED_PARAM = 'UNDEFINED PARAM'
CONSTANT.STATUS_REQUEST_ERROR   = 'REQUEST ERROR'
CONSTANT.STATUS_OK              = 'OK'

CONSTANT.REQUEST_TIMEOUT = 1

CONSTANT.ROLE_API = 'api'

return CONSTANT
